timesheet/userprofile/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.views import *
from django.conf import settings

urlpatterns = patterns('',
    # Private profile
    url(r'^profile/$', overview, name='profile_overview'),

    url(r'^profile/edit/location/$', location, name='profile_edit_location'),

    url(r'^profile/edit/personal/$', personal, name='profile_edit_personal'),

    url(r'^profile/delete/$', delete, name='profile_delete'),

    url(r'^profile/timesheet/$', timesheet, name='profile_timesheet'),

    url(r'^profile/score/$', score, name='profile_score'),

    url(r'^profile/score/delete/(?P<id>.+)/$', delete_score),

    # Avatars
    url(r'^profile/edit/avatar/delete/$', avatardelete,
        name='profile_avatar_delete'),

    url(r'^profile/edit/avatar/$', avatarchoose, name='profile_edit_avatar'),

    url(r'^profile/edit/avatar/crop/$', avatarcrop,
        name='profile_avatar_crop'),

    url(r'^profile/edit/avatar/crop/done/$', direct_to_template,
        { 'extra_context': {'section': 'avatar'},
        'template': 'userprofile/avatar/done.html'},
        name='profile_avatar_crop_done'),
    
    url(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),

    # Account utilities
    url(r'^email/validation/$', email_validation, name='email_validation'),

    url(r'^email/validation/processed/$', direct_to_template,
        {'template': 'userprofile/account/email_validation_processed.html'},
        name='email_validation_processed'),

    url(r'^email/validation/(?P<key>.{70})/$', email_validation_process,
        name='email_validation_process'),

    url(r'^email/validation/reset/$', email_validation_reset,
        name='email_validation_reset'),

    url(r'^email/validation/reset/(?P<action>done|failed)/$',
        direct_to_template,
        {'template' : 'userprofile/account/email_validation_reset_response.html'},
        name='email_validation_reset_response'),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'userprofile/account/password_reset.html',
         'email_template_name': 'userprofile/email/password_reset_email.txt' },
        name='password_reset'),

    url(r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'userprofile/account/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password/change/$', 'django.contrib.auth.views.password_change',
        {'template_name': 'userprofile/account/password_change.html'},
        name='password_change'),

    url(r'^password/change/done/$',
        'django.contrib.auth.views.password_change_done',
        {'template_name': 'userprofile/account/password_change_done.html'},
        name='password_change_done'),

    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'userprofile/account/password_reset_confirm.html'},
        name="password_reset_confirm"),

    url(r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'userprofile/account/password_reset_complete.html'},
        name="password_reset_complete"),

    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'userprofile/account/login.html'},
        name='login'),

    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'userprofile/account/logout.html'},
        name='logout'),

    # Registration
    url(r'^register/$', register, name='signup'),

    url(r'^register/validate/$', direct_to_template,
        {'template' : 'userprofile/account/validate.html'},
        name='signup_validate'),

    url(r'^register/complete/$', direct_to_template,
        {'extra_context': { 'email_validation_required': hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION },
         'template': 'userprofile/account/registration_done.html'},
        name='signup_complete'),

    # Users public profile
    url(r'^profile/(?P<username>.+)/$', public, name='profile_public'),

)

timesheet/userprofile/models.py
# coding=UTF-8
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from django.template import loader, Context
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings
from django.core.files.storage import default_storage
if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
    try:
        from backends.S3Storage import S3Storage
        storage = S3Storage()
    except ImportError:
        raise S3BackendNotFound
else:
    storage = default_storage
import datetime
import cPickle as pickle
import base64
import urllib
import os.path
try:
    from PIL import Image, ImageFilter
except ImportError:
    import Image, ImageFilter

AVATAR_SIZES = (128, 96, 64, 48, 32, 24, 16)

class BaseProfile(models.Model):
    """
    User profile model
    """

    user = models.ForeignKey(User, unique=True)
    creation_date = models.DateTimeField(default=datetime.datetime.now)
    latitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True)

    class Meta:
        abstract = True

    def has_avatar(self):
        return Avatar.objects.filter(user=self.user, valid=True).count()

    def __unicode__(self):
        return _("%s's profile") % self.user

    def get_absolute_url(self):
        return reverse("profile_public", args=[self.user])


class Avatar(models.Model):
    """
    Avatar model
    """
    image = models.ImageField(upload_to="avatars/%Y/%b/%d", storage=storage)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    valid = models.BooleanField()

    class Meta:
        unique_together = (('user', 'valid'),)

    def __unicode__(self):
        return _("%s's Avatar") % self.user

    def delete(self):
        if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
            path = urllib.unquote(self.image.name)
        else:
            path = self.image.path

        base, filename = os.path.split(path)
        name, extension = os.path.splitext(filename)
        for key in AVATAR_SIZES:
            try:
                storage.delete(os.path.join(base, "%s.%s%s" % (name, key, extension)))
            except:
                pass

        super(Avatar, self).delete()

    def save(self):
        for avatar in Avatar.objects.filter(user=self.user, valid=self.valid).exclude(id=self.id):
            if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
                path = urllib.unquote(self.image.name)
            else:
                path = avatar.image.path

            base, filename = os.path.split(path)
            name, extension = os.path.splitext(filename)
            for key in AVATAR_SIZES:
                try:
                    storage.delete(os.path.join(base, "%s.%s%s" % (name, key, extension)))
                except:
                    pass
            avatar.delete()

        super(Avatar, self).save()


class EmailValidationManager(models.Manager):
    """
    Email validation manager
    """
    def verify(self, key):
        try:
            verify = self.get(key=key)
            if not verify.is_expired():
                verify.user.email = verify.email
                if hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION:
                    verify.user.is_active = True
                verify.user.save()
                verify.delete()
                return True
            else:
                verify.delete()
                return False
        except:
            return False

    def getuser(self, key):
        try:
            return self.get(key=key).user
        except:
            return False

    def add(self, user, email):
        """
        Add a new validation process entry
        """
        while True:
            key = User.objects.make_random_password(70)
            try:
                EmailValidation.objects.get(key=key)
            except EmailValidation.DoesNotExist:
                self.key = key
                break

        template_body = "userprofile/email/validation.txt"
        template_subject = "userprofile/email/validation_subject.txt"
        site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
        body = loader.get_template(template_body).render(Context(locals()))
        subject = loader.get_template(template_subject).render(Context(locals())).strip()
        send_mail(subject=subject, message=body, from_email=None, recipient_list=[email])
        user = User.objects.get(username=str(user))
        self.filter(user=user).delete()
        return self.create(user=user, key=key, email=email)

class EmailValidation(models.Model):
    """
    Email Validation model
    """
    user = models.ForeignKey(User, unique=True)
    email = models.EmailField(blank=True)
    key = models.CharField(max_length=70, unique=True, db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = EmailValidationManager()

    def __unicode__(self):
        return _("Email validation process for %(user)s") % { 'user': self.user }

    def is_expired(self):
        return (datetime.datetime.today() - self.created).days > 0

    def resend(self):
        """
        Resend validation email
        """
        template_body = "userprofile/email/validation.txt"
        template_subject = "userprofile/email/validation_subject.txt"
        site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
        key = self.key
        body = loader.get_template(template_body).render(Context(locals()))
        subject = loader.get_template(template_subject).render(Context(locals())).strip()
        send_mail(subject=subject, message=body, from_email=None, recipient_list=[self.email])
        self.created = datetime.datetime.now()
        self.save()
        return True

class UserProfileMediaNotFound(Exception):
    pass

class S3BackendNotFound(Exception):
    pass

class GoogleDataAPINotFound(Exception):
    pass

timesheet/userprofile/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.models import User, SiteProfileNotAvailable
from userprofile.models import EmailValidation
from django.core.files.uploadedfile import SimpleUploadedFile
import mimetypes, urllib

if not settings.AUTH_PROFILE_MODULE:
    raise SiteProfileNotAvailable
try:
    app_label, model_name = settings.AUTH_PROFILE_MODULE.split('.')
    Profile = models.get_model(app_label, model_name)
except (ImportError, ImproperlyConfigured):
    raise SiteProfileNotAvailable


from datetime import datetime
from demo.demoprofile.models import Preferences

class LocationForm(forms.ModelForm):
    """
    Profile location form
    """

    class Meta:
        model = Profile
        fields = ('location', 'latitude', 'longitude')

class ProfileForm(forms.ModelForm):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'location', 'latitude', 'longitude',
                   'user', 'public', 'site')

class PublicFieldsForm(forms.ModelForm):
    """
    Public Fields of the Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'user', 'public')

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField(required=False)
    url = forms.URLField(required=False)

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if not url: return ''
        filename, headers = urllib.urlretrieve(url)
        if not mimetypes.guess_all_extensions(headers.get('Content-Type')):
            raise forms.ValidationError(_('The file type is invalid: %s' % type))
        return SimpleUploadedFile(filename, open(filename).read(), content_type=headers.get('Content-Type'))

    def clean(self):
        if not (self.cleaned_data.get('photo') or self.cleaned_data.get('url')):
            raise forms.ValidationError(_('You must enter one of the options'))
        return self.cleaned_data

class AvatarCoordinateField(forms.IntegerField):
    def clean(self, value):
        try:
            value = int(float(value))
        except:
            pass
        return super(AvatarCoordinateField, self).clean(value)

class AvatarCropForm(forms.Form):
    """
    Crop dimensions form
    """
    top = AvatarCoordinateField()
    bottom = AvatarCoordinateField()
    left = AvatarCoordinateField()
    right = AvatarCoordinateField()

    def __init__(self, image=None, *args, **kwargs):
        self.image = image
        super(AvatarCropForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.cleaned_data.get('right') and self.cleaned_data.get('left') and \
           int(self.cleaned_data.get('right')) - int(self.cleaned_data.get('left')) < 96:
            raise forms.ValidationError(_("You must select a portion of the image with a minimum of 96x96 pixels."))

        return self.cleaned_data

class RegistrationForm(forms.Form):

    username = forms.CharField(max_length=255, min_length = 3, label=_("Username"))
    email = forms.EmailField(required=hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION or False, label=_("E-mail address"))
    password1 = forms.CharField(widget=forms.PasswordInput, label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput, label=_("Password (again)"))

    def clean_username(self):
        """
        Verify that the username isn't already registered
        """
        username = self.cleaned_data.get("username")
        if not set(username).issubset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"):
            raise forms.ValidationError(_("That username has invalid characters. The valid values are letters, numbers and underscore."))

        if User.objects.filter(username__iexact=username).count() == 0:
            return username
        else:
            raise forms.ValidationError(_("The username is already registered."))

    def clean(self):
        """
        Verify that the 2 passwords fields are equal
        """
        if self.cleaned_data.get("password1") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise forms.ValidationError(_("The passwords inserted are different."))

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")

        if not email: return  email

        try:
            User.objects.get(email__iexact=email)
            raise forms.ValidationError(_("That e-mail is already used."))
        except User.DoesNotExist:
            try:
                EmailValidation.objects.get(email=email)
                raise forms.ValidationError(_("That e-mail is already being confirmed."))
            except EmailValidation.DoesNotExist:
                return email

class EmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if not (User.objects.filter(email=email) or EmailValidation.objects.filter(email=email)):
            return email

        raise forms.ValidationError(_("That e-mail is already used."))

class ResendEmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email) or EmailValidation.objects.filter(email=email):
            return email

        raise forms.ValidationError(_("That e-mail isn't registered."))


class DateForm(forms.Form):
    timestamp = forms.DateField(initial=datetime.today())
   
class ScoreForm(forms.ModelForm):
    class Meta:
        model = Preferences
        fields = ('application', 'score')

timesheet/userprofile/templates/userprofile/profile/delete.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Delete personal information" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="" method="post" enctype="multipart/form-data">
		<fieldset>
			<legend>{% trans "Delete your personal information" %}</legend>
			<p><label for="remove">{% trans "Are you sure?" %}</label> <input id="remove" type="submit" value="{% trans "Yes" %}" /></p>
		</fieldset>
	</form>
{% endblock %}

{% block userprofile_content_related %}
	<div class="box">
		<h3>{% trans "Remove profile" %}</h3>
		<p>{% trans "It erases all your private data except your username. You can refill the information later if you want to" %}.</p>
	</div>
{% endblock %}

timesheet/userprofile/templates/userprofile/profile/location.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}{{ user }}'s Dashboard{% endblocktrans %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
	{% if GOOGLE_MAPS_API_KEY %}
	<script type="text/javascript" src="{{ MEDIA_URL }}userprofile/js/jquery.location.js"></script>
	{% endif %}
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="{{ request.path_info }}" method="post" enctype="multipart/form-data">
	{{ form.errors }}
	<fieldset>
		<legend>{% trans "Define your location" %}{% if geoip %} (<a href="?ip=1">{% trans "Auto-discover location" %}</a>){% endif %}</legend>
		<label for="id_country">{% trans "Country" %}<img class="hide loading" alt="{% trans "Loading..." %}" src="{{ MEDIA_URL }}userprofile/images/loading.gif" /></label>
		<p>{{ form.country }}</p>
		{% if GOOGLE_MAPS_API_KEY %}
			<div class="mapinfo">
				<p><label>{% trans "Location:" %}</label> <span id="location_info">{{ form.instance.location }}</span></p>
				<label for="map">{% trans "Position" %}</label>
				<div id="map"></div>
			</div>
			<div class="hide">{{ form.location }}{{ form.latitude }}{{ form.longitude }}</div>
			<input type='hidden' name='_apikey' id="google_maps_apikey" value="{{ GOOGLE_MAPS_API_KEY }}" />
			<input type='hidden' name='_fetch_geodata_url' id="fetch_geodata_url" value="{% url profile_geocountry_info 0 0  %}" />
		{% endif %}
	</fieldset>
	<p><input type="submit" value="{% trans 'Save' %}" /></p>
	</form>
{% endblock %}
{% block userprofile_content_related %}
<div class="box">
  <h3>{% trans "Location information" %}</h3>
    <p>{% trans "Define your location information" %}.</p>
</div>
{% endblock %}

timesheet/userprofile/templates/userprofile/profile/overview.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Overview of your profile" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
  <script type="text/javascript">
  </script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	{% load avatars %}
	<form action="" method="post">
	<fieldset>
		<legend>{% trans "Overview of your profile" %}</legend>
		<div id="avatar" class="{{ css_classes.overview_avatar }} center">
			<a href="{% url profile_edit_avatar %}">
				<img class="border" src="{% avatar 96 %}" />
			</a>
			<p><a href="{% url profile_edit_avatar %}">{% if user.get_profile.has_avatar %}{% trans "Change avatar" %}{% else %}{% trans "Add avatar" %}{% endif %}</a></p>
		</div>
	
		<div class="{{ css_classes.overview_details }}">
			<p><label for="id_user">{% trans "Username:" %}</label> {{ user }}</p>
			<p><label for="id_email">{% trans "E-mail:" %}</label>
				<span class="{% if not email or not validated %}quiet red{% endif %}">
				{%if not email %}{% trans "Not set yet" %}
				{% else %}{{ email }}
				{% if not validated %}{% trans " (Not validated)" %}
				{% endif %}{% endif %}
				</span>
			</p>
		</div>
	</fieldset>
	</form>
{% endblock %}

{% block userprofile_content_related %}
	<div class="box">
		<h3>{% trans "Management:" %}</h3>
		<a href="{% url password_change %}">{% trans "Change password" %}</a>
		<br />
		<a href="{% url email_validation %}">{% if email %}{% trans "Change your e-mail address" %}{% else %}{% trans "Add your e-mail address" %}{% endif %}</a>
		{% if not validated and email %}<br /><a href="{% url email_validation_reset %}">{% trans "Resend validation e-mail" %}</a>
		{% endif %}
		<br />
		{% if not user.get_profile.location %}
			<a href="{% url profile_edit_location %}">{% trans "Add location" %}</a>
		{% else %}
			<a href="{% url profile_edit_location %}">{% trans "Change location" %}</a>
		{% endif %}
	</div>
{% endblock %}

timesheet/userprofile/templates/userprofile/profile/personal.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Edit your personal information" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extracss %}
	<link rel="stylesheet" href="{{ MEDIA_URL }}userprofile/css/ui.datepicker.css" type="text/css" />
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
	$(function() {
		$("input[type='text']").addClass("text");
		$("form input")[0].focus();
	});
</script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form class="personal" action="{{ request.path_info }}" method="post" enctype="multipart/form-data">
	<fieldset>
		<legend>{% trans "Edit your personal information" %}</legend>
		{{ form.as_p }}
	</fieldset>
  <input type="submit" value="{% trans 'Save' %}" />
	</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>{% trans "Personal information" %}</h3>
    <p>{% trans "Insert some information about you" %}.</p>
  </div>
{% endblock %}

timesheet/userprofile/templates/userprofile/profile/public.html
{% extends "userprofile/base.html" %}
{% load i18n %}
{% load avatars %}

{% block title %}{{ profile.user }}'s public profile{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
	{% if profile.latitude and profile.longitude %}
	<script type="text/javascript" src="http://www.google.com/jsapi?key={{ GOOGLE_MAPS_API_KEY }}"></script>
	<script type="text/javascript">google.load("maps", "2");</script>
	<script type="text/javascript">
		$(function() {
		if (google.maps.BrowserIsCompatible()) {
			var map = new google.maps.Map2(document.getElementById("map"));
      map.disableDragging();
			map.setCenter(new google.maps.LatLng({{ profile.latitude }}, {{ profile.longitude }}), 4);
			var marker = new google.maps.Marker(new google.maps.LatLng({{ profile.latitude }}, {{ profile.longitude }}), {clickable: false });
			map.addOverlay(marker);
		}
		});
	</script>
	{% endif %}
{% endblock %}

{% block userprofile_content %}
	<h2>{% blocktrans with profile.user as user %}Public profile of {{ user }}{% endblocktrans %}</h2>

	<div class="vcard">
		<div class="{{ css_classes.public_vcard_content }}">
			<img class="border top" alt="{{ profile.user }}" src="{% avatar 96 profile.user %}" />
			<ul>
				<li>{% trans "Username" %}: <strong>{{ profile.user }}</strong></li>
				{% if profile.country %}
				<li>{% trans "Country" %}: <strong>{{ profile.get_country_display }}</strong></li>
				{% endif %}
				{% if profile.location %}
				<li>{% trans "Location" %}: <strong>{{ profile.location }}</strong></li>
				{% endif %}
			</ul>
		</div>
		{% if profile.latitude and profile.longitude %}
		<div class="{{ css_classes.public_vcard_map }}">
			<div id="map"></div>
		</div>
		{% endif %}
	</div>
{% endblock %}

timesheet/userprofile/templates/userprofile/profile/timesheet.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Overview of your profile" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extracss %}
	<link rel="stylesheet" href="{{ MEDIA_URL }}userprofile/css/ui.datepicker.css" type="text/css" />
{% endblock %}

{% block extrajs %}
  <script type="text/javascript" src="{{ MEDIA_URL }}userprofile/js/ui.datepicker.js"></script>
  <script type="text/javascript">
$(function () {
$("#id_timestamp").addClass("hide");
$("#id_timestamp").before('<div class="calendar"></div>');

	var date = $("#id_timestamp").val().split("-");
  $("div.calendar").datepicker({ onSelect: updateInline, hideIfNoPrevNext: true, yearRange: "1940:2010", defaultDate: new Date(date[0],date[1] -1, date[2]) });

	function updateInline(dateStr) {
		var arrdate = dateStr.split("/");
		$("#id_timestamp").val(arrdate[2] + "-" + arrdate[0] + "-" + arrdate[1]);
	}

    var data1 = {{ time_array }};

var options1 = {
      xaxis: { mode: "time" },
      yaxis: { min: -2, max: 2 , ticks:[[-1, "unproductive"],[0, "neutral"],[1, "productive"]]}
  };    
    $.plot($("#placeholder1"), [data1], options1);

    var dxx = {{ app_pc }};

var bar_options = {
        yaxis: { min: 1, max: 30 },
        xaxis: { min: 1, max: 15 , ticks: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]},
        bars: { show: true, fill: true, fillColor: "rgba(255, 47, 47, 0.8)" }
}
    $.plot($("#splitup"), [dxx], bar_options);
});
  </script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
    <h1>{{ user.username }}</h1>

    <div id="placeholder1" style="width:500px;height:150px;"></div>

    <p>Effective time clocked: <b>{{ effective_hrs }}</b> hours, <b>{{ effective_min }}</b> minutes</p>
    <p>Total time clocked: <b>{{ total_hrs }}</b> hours, <b>{{ total_min }}</b> minutes</p>
    <p>Gaps indicate period of inactivity.</p>

    <div id="splitup" style="width:500px;height:400px;"></div>

<h3> Legend: </h3>

{% for each_entry in app_bar %}
<p>{{ forloop.counter }} - {{ each_entry.appname }}</p>
{% endfor %}

{% endblock %}

{% block userprofile_content_related %}

	<form class="personal" action="{{ request.path_info }}" method="post" enctype="multipart/form-data">
	<fieldset>
		<legend>{% trans "Select a date to view  the timesheet:" %}</legend>
		  {{ dateForm.as_p }}
		<input type="submit" value="{% trans 'Go' %}" />
	</fieldset>
	</form>

	<div class="box">
		<h3>{% trans "Management:" %}</h3>
		<a href="{% url password_change %}">{% trans "Change password" %}</a>
		<br />
		<a href="{% url email_validation %}">{% if email %}{% trans "Change your e-mail address" %}{% else %}{% trans "Add your e-mail address" %}{% endif %}</a>
		{% if not validated and email %}<br /><a href="{% url email_validation_reset %}">{% trans "Resend validation e-mail" %}</a>
		{% endif %}
		<br />
		{% if not user.get_profile.location %}
			<a href="{% url profile_edit_location %}">{% trans "Add location" %}</a>
		{% else %}
			<a href="{% url profile_edit_location %}">{% trans "Change location" %}</a>
		{% endif %}
	</div>
{% endblock %}