timesheet/userprofile/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.views import *
from django.conf import settings

urlpatterns = patterns('',
    # Private profile
    url(r'^profile/$', overview, name='profile_overview'),

    url(r'^profile/edit/location/$', location, name='profile_edit_location'),

    url(r'^profile/edit/personal/$', personal, name='profile_edit_personal'),

    url(r'^profile/delete/$', delete, name='profile_delete'),

    url(r'^profile/timesheet/$', timesheet, name='profile_timesheet'),

    url(r'^profile/score/$', score, name='profile_score'),

    url(r'^profile/score/delete/(?P<id>.+)/$', delete_score),

    # Avatars
    url(r'^profile/edit/avatar/delete/$', avatardelete,
        name='profile_avatar_delete'),

    url(r'^profile/edit/avatar/$', avatarchoose, name='profile_edit_avatar'),

    url(r'^profile/edit/avatar/crop/$', avatarcrop,
        name='profile_avatar_crop'),

    url(r'^profile/edit/avatar/crop/done/$', direct_to_template,
        { 'extra_context': {'section': 'avatar'},
        'template': 'userprofile/avatar/done.html'},
        name='profile_avatar_crop_done'),
    
    url(r'^my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),

    # Account utilities
    url(r'^email/validation/$', email_validation, name='email_validation'),

    url(r'^email/validation/processed/$', direct_to_template,
        {'template': 'userprofile/account/email_validation_processed.html'},
        name='email_validation_processed'),

    url(r'^email/validation/(?P<key>.{70})/$', email_validation_process,
        name='email_validation_process'),

    url(r'^email/validation/reset/$', email_validation_reset,
        name='email_validation_reset'),

    url(r'^email/validation/reset/(?P<action>done|failed)/$',
        direct_to_template,
        {'template' : 'userprofile/account/email_validation_reset_response.html'},
        name='email_validation_reset_response'),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'userprofile/account/password_reset.html',
         'email_template_name': 'userprofile/email/password_reset_email.txt' },
        name='password_reset'),

    url(r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'userprofile/account/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password/change/$', 'django.contrib.auth.views.password_change',
        {'template_name': 'userprofile/account/password_change.html'},
        name='password_change'),

    url(r'^password/change/done/$',
        'django.contrib.auth.views.password_change_done',
        {'template_name': 'userprofile/account/password_change_done.html'},
        name='password_change_done'),

    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'userprofile/account/password_reset_confirm.html'},
        name="password_reset_confirm"),

    url(r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'userprofile/account/password_reset_complete.html'},
        name="password_reset_complete"),

    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'userprofile/account/login.html'},
        name='login'),

    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'userprofile/account/logout.html'},
        name='logout'),

    # Registration
    url(r'^register/$', register, name='signup'),

    url(r'^register/validate/$', direct_to_template,
        {'template' : 'userprofile/account/validate.html'},
        name='signup_validate'),

    url(r'^register/complete/$', direct_to_template,
        {'extra_context': { 'email_validation_required': hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION },
         'template': 'userprofile/account/registration_done.html'},
        name='signup_complete'),

    # Users public profile
    url(r'^profile/(?P<username>.+)/$', public, name='profile_public'),

)

timesheet/userprofile/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.models import User, SiteProfileNotAvailable
from userprofile.models import EmailValidation
from django.core.files.uploadedfile import SimpleUploadedFile
import mimetypes, urllib

if not settings.AUTH_PROFILE_MODULE:
    raise SiteProfileNotAvailable
try:
    app_label, model_name = settings.AUTH_PROFILE_MODULE.split('.')
    Profile = models.get_model(app_label, model_name)
except (ImportError, ImproperlyConfigured):
    raise SiteProfileNotAvailable


from datetime import datetime
from demo.demoprofile.models import Preferences

class LocationForm(forms.ModelForm):
    """
    Profile location form
    """

    class Meta:
        model = Profile
        fields = ('location', 'latitude', 'longitude')

class ProfileForm(forms.ModelForm):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'location', 'latitude', 'longitude',
                   'user', 'public', 'site')

class PublicFieldsForm(forms.ModelForm):
    """
    Public Fields of the Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'user', 'public')

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField(required=False)
    url = forms.URLField(required=False)

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if not url: return ''
        filename, headers = urllib.urlretrieve(url)
        if not mimetypes.guess_all_extensions(headers.get('Content-Type')):
            raise forms.ValidationError(_('The file type is invalid: %s' % type))
        return SimpleUploadedFile(filename, open(filename).read(), content_type=headers.get('Content-Type'))

    def clean(self):
        if not (self.cleaned_data.get('photo') or self.cleaned_data.get('url')):
            raise forms.ValidationError(_('You must enter one of the options'))
        return self.cleaned_data

class AvatarCoordinateField(forms.IntegerField):
    def clean(self, value):
        try:
            value = int(float(value))
        except:
            pass
        return super(AvatarCoordinateField, self).clean(value)

class AvatarCropForm(forms.Form):
    """
    Crop dimensions form
    """
    top = AvatarCoordinateField()
    bottom = AvatarCoordinateField()
    left = AvatarCoordinateField()
    right = AvatarCoordinateField()

    def __init__(self, image=None, *args, **kwargs):
        self.image = image
        super(AvatarCropForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.cleaned_data.get('right') and self.cleaned_data.get('left') and \
           int(self.cleaned_data.get('right')) - int(self.cleaned_data.get('left')) < 96:
            raise forms.ValidationError(_("You must select a portion of the image with a minimum of 96x96 pixels."))

        return self.cleaned_data

class RegistrationForm(forms.Form):

    username = forms.CharField(max_length=255, min_length = 3, label=_("Username"))
    email = forms.EmailField(required=hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION or False, label=_("E-mail address"))
    password1 = forms.CharField(widget=forms.PasswordInput, label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput, label=_("Password (again)"))

    def clean_username(self):
        """
        Verify that the username isn't already registered
        """
        username = self.cleaned_data.get("username")
        if not set(username).issubset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_"):
            raise forms.ValidationError(_("That username has invalid characters. The valid values are letters, numbers and underscore."))

        if User.objects.filter(username__iexact=username).count() == 0:
            return username
        else:
            raise forms.ValidationError(_("The username is already registered."))

    def clean(self):
        """
        Verify that the 2 passwords fields are equal
        """
        if self.cleaned_data.get("password1") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise forms.ValidationError(_("The passwords inserted are different."))

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")

        if not email: return  email

        try:
            User.objects.get(email__iexact=email)
            raise forms.ValidationError(_("That e-mail is already used."))
        except User.DoesNotExist:
            try:
                EmailValidation.objects.get(email=email)
                raise forms.ValidationError(_("That e-mail is already being confirmed."))
            except EmailValidation.DoesNotExist:
                return email

class EmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if not (User.objects.filter(email=email) or EmailValidation.objects.filter(email=email)):
            return email

        raise forms.ValidationError(_("That e-mail is already used."))

class ResendEmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email) or EmailValidation.objects.filter(email=email):
            return email

        raise forms.ValidationError(_("That e-mail isn't registered."))


class DateForm(forms.Form):
    timestamp = forms.DateField(initial=datetime.today())
   
class ScoreForm(forms.ModelForm):
    class Meta:
        model = Preferences
        fields = ('application', 'score')

timesheet/userprofile/templates/userprofile/avatar/choose.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Choose the location of your avatar" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
<script type="text/javascript">
	$(function() {
	//avatar
		$("a.delavatar").click(function() {
			$.getJSON($(this).attr("href"), function(data) {
				if (data.success) {
					$("img#avatarimg").attr("src", "{{ generic96 }}");
					$("p#avatardelete").remove();
				}
			});
			return false;
		});

    $("div.photos a").click(function() {
      $("form input[name='url']").val($(this).attr("href"));
      $("form").submit();
      return false;
    });

	});
</script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form action="{% url profile_edit_avatar %}" method="post" accept-charset="utf-8" enctype="multipart/form-data">
		<fieldset>
			<legend>{% trans "Choose the location of your avatar" %}</legend>
			<ul>
			<li>
				<label for="id_photo">{% trans "Select an image from disk" %}:</label>
				<p>{{ form.photo }}
				<input type="submit" value="{% trans 'Done' %}" />
				</p>
			</li>
			<li>
				<label for="id_url">{% trans "Select an image from a remote URL. Put the URL on the input below and the image will be retrieved for you" %}:</label>
				<p>{{ form.url }}
				<input type="submit" value="{% trans 'Done' %}" />
				</p>
			</li>
			</ul>
			{% if form.errors %}
			{% for error,desc in form.errors.items %}
			<p class="small quiet red">* {{desc|join:"; "}}</p>
			{% endfor %}
			{% endif %}
		</fieldset>
</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
		<p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

	{% load avatars %}
  <div class="center">
		<img class="border" alt="{{ request.user }}" id="avatarimg" src="{% avatar 96 %}" />
    {% if user.get_profile.has_avatar %}<p id="avatardelete" style="text-align: center;"><a href="{{ request.path_info }}delete/" class="delavatar">{% trans "Delete" %}</a></p>{% endif %}
	</div>
{% endblock %}

timesheet/userprofile/templates/userprofile/avatar/crop.html
{% extends "userprofile/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Crop &amp; resize the area you want" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{{ MEDIA_URL }}userprofile/js/jquery.imgareaselect-0.8.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}userprofile/js/jquery.crop.js"></script>
{% endblock %}

{% block userprofile_navigation %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block userprofile_content %}
	<form name="cropavatar" action="{{ request.path_info }}" method="post" accept-charset="utf-8">
	<fieldset>
		<legend style='display:none'>{% trans "Crop &amp; resize the area you want" %}</legend>

		{% if form.errors %}
			{% for error,desc in form.errors.items %}
				<p class="error">{{desc|join:"; "}}</p>
			{% endfor %}
		{% endif %}

		<div style="text-align: center;">
			<img src="{{ avatar.image.url }}" id="cropimage" />
		</div>
		<input type="hidden" name="top" value="0"/>
		<input type="hidden" name="bottom" value="0"/>
		<input type="hidden" name="left" value="0"/>
		<input type="hidden" name="right" value="0"/>
	</fieldset>
	<input type="submit" class="done" value="{% trans 'Done' %}" />
	</form>
{% endblock %}

{% block userprofile_content_related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
    <p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

  {% load avatars %}
  <div class="center" id="avatarimg_container">
    <img class="border" id="avatarimg" src="{% avatar 96 %}" />
  </div>

{% endblock %}